networks:
  app-network:
    driver: bridge
services:
  app:
    container_name: laravel_blog
    image: laravel-blog
    working_dir: /var/www
    build:
      context: ./infra/app
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
    networks:
      - app-network
  db:
    container_name: pgsql
    image: postgres:16
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - app-network
  nginx:
    image: nginx:1.27.3-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 8100:80
    volumes:
      - ./:/var/www
      - ./infra/nginx/conf:/etc/nginx/conf.d
    networks:
      - app-network
volumes:
  db-data: {}
